apiVersion: v1
kind: Service
metadata:
  name: {{ include "fs-mqtt.fullname" . }}
  labels:
    {{- include "fs-mqtt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.mqtt.port }}
      targetPort: 1883 
      protocol: TCP
      name: {{ .Values.service.mqtt.name }}
      nodePort: {{ .Values.service.mqtt.nodePort }}
    - port: {{ .Values.service.websocket.port }}
      targetPort: 9001 
      protocol: TCP
      name: {{ .Values.service.websocket.name }} 
      nodePort: {{ .Values.service.websocket.nodePort }}
  selector:
    {{- include "fs-mqtt.selectorLabels" . | nindent 4 }}
